### ISSUE TITLE
reasonable command line parsing

### ISSUE THREAD

**Issue by dcbaker** [cps-org/cps-config#13]
The current command line parsing solution is very much a "get us going" sort of solution. We need something better for the future.

**Comment by lunacd** [comment]
Is there a preferred library to use for this? Maybe cxxopts?

**Comment by dcbaker** [comment]
I don't personally have a preferences, my only concerns are MIT compatibly licensed and is well supported. If it doesn't have Meson support let me know so I can add wrap support for the Meson build.

**Comment by lunacd** [comment]
[cxxopts](https://github.com/jarro2783/cxxopts) is MIT-licensed and is wrapdb. In fact that's how I found that library in the first place.

**Comment by bretbrownjr** [comment]
For now, whatever keeps us productive is great. Probably anything with a good license that is reasonably widely packaged (Ubuntu, debian, Conan, etc.) is fine.

Long-term, we may want to strip cps-config down to the bare essentials, dependency wise, so it's available to the most environments possible. It may be interesting to be written in C99, even.

But let's get to a release of the CPS spec and some nontrivial usage first. The main benefit of cps-config right now is teaching us about how CPS should work.

**Comment by dcbaker** [comment]
I think cxxopts is fine, as long as you don't use ICU. I found some interesting bugs there: https://github.com/jarro2783/cxxopts/pull/423

The wrap is a little out of date, if we plan to use it for cps-config I'll write up a more complete meson implementation and see if the maintainer will take it, since they already have bazel definitions
