### ISSUE TITLE
Use docker Images for CI

### ISSUE THREAD

**Issue by dcbaker** [cps-org/cps-config#21]
There are a couple of things worth doing here:
 - [ ] allow building on more distros that just ubuntu. It would be great to have at least fedora and arch supported
 - [ ] speed up CI by not needing to install packages at the start of each job

**Comment by bretbrownjr** [comment]
You want:

```
* [ ] this a list entry with a checkbox
```

Not:

```
* [] This is a bullet point with some leading square brackets
```

...if you're OK sharing sufficient repo privileges, I'll sneakily correct markdown in issues without posting comments. 😏

**Comment by dcbaker** [comment]
Fixed that, I think I gave you the correct permissions. I have to run ATM, but I'll be back later if that didn't work.

**Comment by bretbrownjr** [comment]
I see an edit button on the issue now. Thanks.
